ElasticSearch.Web/Models/ErrorViewModel.cs
namespace ElasticSearch.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ElasticSearch.Web/Controllers/BlogController.cs
using ElasticSearch.Web.Model;
using ElasticSearch.Web.Services;
using ElasticSearch.Web.ViewMoels;
using Microsoft.AspNetCore.Mvc;

namespace ElasticSearch.Web.Controllers
{
    public class BlogController : Controller
    {
        private readonly BlogService _blogService;

        public BlogController(BlogService blogService)
        {
            _blogService = blogService;
        }
        [HttpGet]
        public IActionResult Search()
        {
            return View(new List<Blog>());
        }
        [HttpPost]
        public async Task<IActionResult> Search(string searchText)
        {
            var blogList=await _blogService.SearchAsync(searchText);
            return View(blogList);
        }

        [HttpGet]
        public IActionResult Save()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Save(BlogCreateViewModel model)
        {
           var isSucces= await _blogService.SaveAsync(model);
            if (!isSucces)
            {
                TempData["result"] = "başarısız";
                return RedirectToAction("ZAZAZAZZAZA");
            }
            TempData["result"] = "başarılı";
            return RedirectToAction("lololololollo");
        }
    }
}

ElasticSearch.Web/Controllers/ECommerceController.cs
using ElasticSearch.Web.Services;
using ElasticSearch.Web.ViewMoels;
using Microsoft.AspNetCore.Mvc;

namespace ElasticSearch.Web.Controllers
{
    public class ECommerceController : Controller
    {
        private readonly ECommerceService _service;

        public ECommerceController(ECommerceService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Search([FromQuery] SeachPageViewModel searchPageView)
        {
            var (eCommerceList,totalCount,pageLinkCount)=await  _service.SearchAsync(searchPageView.SearchViewModel, searchPageView.Page, searchPageView.PageSize);
            searchPageView.List = eCommerceList;
            searchPageView.PageLinkCount = pageLinkCount;
            searchPageView.TotalCount = totalCount;
            return View(searchPageView);
        }
    }
}

ElasticSearch.Web/Controllers/HomeController.cs
using ElasticSearch.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ElasticSearch.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ElasticSearch.Web/Views/Blog/Save.cshtml
@using ElasticSearch.Web.ViewMoels
@model BlogCreateViewModel
@{
    ViewData["Title"] = "Save";
}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h2>Blog Create</h2>

        <form method="post">

            <div class="mb-3">

                <label asp-for="Title" class="form-control"></label>
                <input asp-for="Title" class="form-control" />
            </div>
            <div class="mb-3">
                <label asp-for="Content" class="form-label">Example textarea</label>
                <textarea asp-for="Content" id="exampleFormControlTextarea1" rows="3"></textarea>
            </div>
            <div class="mb-3">
                <label asp-for="Tags" class="form-label">Tags</label>
                <textarea asp-for="Tags" id="exampleFormControlTextarea1" rows="3"></textarea>
            </div>
            <div class="mb-3">
                <button class="btn btn-primary" type="submit">Save</button>
            </div>

        </form>

    </div>
</div>

ElasticSearch.Web/Views/Blog/Search.cshtml
@{
    ViewData["Title"] = "Search";
}
@model List<ElasticSearch.Web.Model.Blog>
<div class="container">
    <div class="col-md-10 offset-1-md-1">
        <form method="post" >
            <div class="mb-3">
                <label>Search(Title,Content)</label>
                <input name="SearchText" class="form-control" />
            </div>

            <button type="submit">Search</button>

        </form>

        @if (!Model.Any())
        {
            <div class="alert alert-info">Sonuç yok</div>
            <h3>ZAAAAAAAAA SONUÇ YOKKKKKK</h3>
        }
        <table class="table">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Title</th>
                    <th>Content</th>
                    <th>UserId</th>
                    <th>Tags</th>
                    <th>Created</th>
                </tr>
            </thead>
            <tbody>
                @foreach(var item in Model)
                {
                    <tr>
                        <td>@item.Id</td>
                        <td>@item.Title</td>
                        <td>@item.Content</td>
                        <td>@item.UserId</td>
                        <td>@String.Join(",",item.Tags)</td>
                        <td>@item.Created.ToShortDateString()</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

ElasticSearch.Web/Views/ECommerce/Search.cshtml
@model ElasticSearch.Web.ViewMoels.SeachPageViewModel
@{
    
}

<div class="container">
    <div class="col-md-4">
        <form method="get" asp-action="Search">
            <div class="mb-3">
                <label asp-for="SearchViewModel.CustomerFullName" class="form-label">customer full name</label>
                <textarea asp-for="SearchViewModel.CustomerFullName" id="exampleFormControlTextarea1" rows="3"></textarea>
            </div>
            <div class="mb-3">
                <label asp-for="SearchViewModel.Category" class="form-control">Kategori</label>
                <input asp-for="SearchViewModel.Category" class="form-control" />
            </div>
            <div class="mb-3">
                <label asp-for="SearchViewModel.Gender" class="form-label">Cinsiyet</label>
                <textarea asp-for="SearchViewModel.Gender" id="exampleFormControlTextarea1" rows="3"></textarea>
            </div>
            <div class="mb-3">
                <label asp-for="SearchViewModel.OrderDateStart" class="form-label">Start Date</label>
                <input asp-for="SearchViewModel.OrderDateStart" type="date" class="form-control" />
            </div>
            <div class="mb-3">
                <label asp-for="SearchViewModel.OrderDateEnd" class="form-label">End Date</label>
                <input asp-for="SearchViewModel.OrderDateEnd" type="date" class="form-control" />
            </div>

            <div class="mb-3">
                <button class="btn btn-primary" type="submit">Search</button>
            </div>
        </form>

    </div>
    <div class="col-md-8">
        <div class="alert alert-success">
            <span>toplam : @Model.TotalCount Kayıt bulunmuştur</span>
        </div>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Customer FullName</th>
                    <th>Order Date</th>
                    <th>Gender</th>
                    <th>TaxfulTotalPrice</th>
                    <th>Category</th>
                    <th>OrderId</th>
                </tr>
            </thead>
            <tbody>
                @foreach(var item in Model.List)
                {
                    <tr>
                        <td>@item.CustomerFullName</td>
                        <td>@item.OrderDate</td>
                        <td>@item.Gender</td>
                        <td>@item.TaxfulTotalPrice</td>
                        <td>@item.Category</td>
                        <td>@item.OrderId</td>
                    </tr>
                }
            </tbody>
        </table>

    </div>
</div>

ElasticSearch.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ElasticSearch.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ElasticSearch.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ElasticSearch.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ElasticSearch.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Blog" asp-action="Save">Blog Save</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Blog" asp-action="Search">Blog Save</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ECommerce" asp-action="Search">ECommerce Search Page</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ElasticSearch.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>